spring:
  profiles:
    enabled: 
    - prod
    - default

application:
  port: 8761
  context: /

server:
  port: ${application.port:8761}
  servlet:
    context-path: ${application.context:/}

eureka:
  instance:
    lease-renewal-interval-in-seconds: 60
  client:
    registerWithEureka: false
    fetchRegistry: false
  #server:
  #  waitTimeInMsWhenSyncEmpty: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"